<marquee>
	<a href="/links.html">
	<font size="4" face="STXingkai">
		<font color="#FF0000">欢</font>
		<font color="#E80017">迎</font>
		<font color="#D1002E">点</font>
		<font color="#BA0045">我</font>
		<font color="#A3005C">互</font>
		<font color="#A00073">换</font>
		<font color="#A0008A">友</font>
		<font color="#A000A1">链</font>
		<font color="#A000B8">哦</font>
		<font color="#A000CF">~</font>
		<font color="#A000E6">~</font>
	</font>
	</a>
</marquee>
